package convert

import (
	"bytes"
	"fmt"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"

	"github.com/goplus/gogen"
	"github.com/goplus/llcppg/ast"
	cfg "github.com/goplus/llcppg/cmd/gogensig/config"
	"github.com/goplus/llcppg/cmd/gogensig/convert/names"
	"github.com/goplus/llcppg/cmd/gogensig/dbg"
	"github.com/goplus/llcppg/cmd/gogensig/errs"
	ctoken "github.com/goplus/llcppg/token"
	"github.com/goplus/mod/gopmod"
)

// In Processing Package
type Package struct {
	*PkgInfo
	p       *gogen.Package // package writer
	conf    *PackageConfig // package config
	cvt     *TypeConv      // package type convert
	curFile *HeaderFile    // current processing c header file.
	files   []*HeaderFile  // header files.

	// incomplete stores type declarations that are not fully defined yet.
	// This is used to handle forward declarations and self-referential types in C/C++.
	incomplete map[string]*Incomplete

	// deferTypes stores type declarations that need to be resolved later.
	// The key is the Go type declaration, and the value is a function that will return
	// the actual type when called.
	// These functions will be executed after all incomplete types are initialized.
	//
	// This is particularly important when handling typedef of incomplete types in Go.
	// In Go, when creating a new type via "type xxx xxx", the underlying type must exist.
	// However, when typedef-ing an incomplete type, its underlying type doesn't exist yet.
	// For such cases, we defer the type initialization until after all incomplete types
	// are properly initialized, at which point we can correctly reference the underlying type.
	deferTypes map[*gogen.TypeDecl]func() (types.Type, error)

	nameMapper *names.NameMapper // handles name mapping and uniqueness
}

type Incomplete struct {
	file   *HeaderFile
	decl   *gogen.TypeDecl // origin name(in c) -> TypeDecl
	typdef *gogen.TypeDefs
	inited bool
}

type PackageConfig struct {
	PkgBase
	Name        string // current package name
	OutputDir   string
	SymbolTable *cfg.SymbolTable
	GenConf     *gogen.Config
}

// When creating a new package for conversion, a Go file named after the package is generated by default.
// If SetCurFile is not called, all type conversions will be written to this default Go file.
func NewPackage(config *PackageConfig) *Package {
	p := &Package{
		p:          gogen.NewPackage(config.PkgPath, config.Name, config.GenConf),
		conf:       config,
		incomplete: make(map[string]*Incomplete),
		deferTypes: make(map[*gogen.TypeDecl]func() (types.Type, error)),
		nameMapper: names.NewNameMapper(),
	}

	mod, err := gopmod.Load(config.OutputDir)
	if err != nil {
		log.Panicf("failed to load mod: %s", err.Error())
	}

	p.PkgInfo = NewPkgInfo(config.PkgPath, config.OutputDir, config.CppgConf, config.Pubs)
	for name, goName := range config.Pubs {
		p.nameMapper.SetMapping(name, goName)
	}

	pkgManager := NewPkgDepLoader(mod, p.p)
	err = pkgManager.InitDeps(p.PkgInfo)
	if err != nil {
		log.Panicf("failed to init deps: %s", err.Error())
	}

	clib := p.p.Import("github.com/goplus/llgo/c")
	typeMap := NewBuiltinTypeMapWithPkgRefS(clib, p.p.Unsafe())
	p.cvt = NewConv(&TypeConfig{
		Types:       p.p.Types,
		TypeMap:     typeMap,
		SymbolTable: config.SymbolTable,
		Package:     p,
	})
	p.SetCurFile(&HeaderFile{File: p.conf.Name})
	return p
}

func (p *Package) SetCurFile(hfile *HeaderFile) {
	var curFile *HeaderFile
	for _, f := range p.files {
		if f.File == hfile.File {
			curFile = f
			break
		}
	}

	if curFile == nil {
		curFile = NewHeaderFile(hfile.File, hfile.IncPath, hfile.IsHeaderFile, hfile.InCurPkg, hfile.IsSys)
		p.files = append(p.files, curFile)
	}

	p.curFile = curFile
	fileName := curFile.ToGoFileName()
	if dbg.GetDebugLog() {
		log.Printf("SetCurFile: %s File in Current Package: %v\n", fileName, curFile.InCurPkg)
	}
	if _, err := p.p.SetCurFile(fileName, true); err != nil {
		log.Panicf("fail to set current file %s\n", curFile.File)
	}
	p.p.Unsafe().MarkForceUsed(p.p)
}

func (p *Package) GetGenPackage() *gogen.Package {
	return p.p
}

func (p *Package) GetOutputDir() string {
	return p.conf.OutputDir
}

func (p *Package) GetTypeConv() *TypeConv {
	return p.cvt
}

// todo(zzy):refine logic
func (p *Package) linkLib(lib string) error {
	if lib == "" {
		return fmt.Errorf("empty lib name")
	}
	linkString := fmt.Sprintf("link: %s;", lib)
	p.p.CB().NewConstStart(types.Typ[types.String], "LLGoPackage").Val(linkString).EndInit(1)
	return nil
}

func (p *Package) newReceiver(typ *ast.FuncType) *types.Var {
	recvField := typ.Params.List[0]
	recvType, err := p.ToType(recvField.Type)
	if err != nil {
		log.Println(err)
	}
	return p.p.NewParam(token.NoPos, "recv_", recvType)
}

func (p *Package) ToSigSignature(recv *types.Var, funcDecl *ast.FuncDecl) (*types.Signature, error) {
	var sig *types.Signature
	var err error
	sig, err = p.cvt.ToSignature(funcDecl.Type, recv)
	if err != nil {
		return nil, err
	}
	return sig, nil
}

func (p *Package) bodyStart(decl *gogen.Func, ret ast.Expr) error {
	if !Expr(ret).IsVoid() {
		retType, err := p.ToType(ret)
		if err != nil {
			return err
		}
		decl.BodyStart(p.p).ZeroLit(retType).Return(1).End()
	} else {
		decl.BodyStart(p.p).End()
	}
	return nil
}

func (p *Package) handleFuncDecl(fnSpec *GoFuncSpec, sig *types.Signature, funcDecl *ast.FuncDecl) error {
	var decl *gogen.Func
	fnPubName := fnSpec.GoSymbName
	if fnSpec.IsMethod {
		decl = p.p.NewFuncDecl(token.NoPos, fnSpec.FnName, sig)
		err := p.bodyStart(decl, funcDecl.Type.Ret)
		if err != nil {
			return err
		}
		// we need to use the actual receiver name in link comment
		// both for value receiver and pointer receiver
		fnPubName = pubMethodName(sig.Recv().Type(), fnSpec)
	} else {
		decl = p.p.NewFuncDecl(token.NoPos, fnPubName, sig)
	}

	doc := CommentGroup(funcDecl.Doc)
	doc.AddCommentGroup(NewFuncDocComments(funcDecl.Name.Name, fnPubName))
	decl.SetComments(p.p, doc.CommentGroup)
	return nil
}

func getNamedType(recvType types.Type) *types.Named {
	switch t := recvType.(type) {
	case *types.Named:
		return t
	case *types.Pointer:
		if named, ok := t.Elem().(*types.Named); ok {
			return named
		}
	}
	return nil
}

// pubMethodName generates a public method name based on the receiver type and function name.
// It handles both pointer and value receivers.
//
// Parameters:
//   - recv: The receiver type from types.Signature
//   - fnName: The base function name
//
// Returns:
//   - For pointer receiver: "(*TypeName).FuncName"
//   - For value receiver: "TypeName.FuncName"
//   - For invalid/unknown receiver: just "FuncName"
func pubMethodName(recv types.Type, fnSpec *GoFuncSpec) string {
	if !fnSpec.IsMethod {
		return fnSpec.FnName
	}
	named := getNamedType(recv)
	if fnSpec.PtrRecv {
		return "(*" + named.Obj().Name() + ")." + fnSpec.FnName
	}
	return named.Obj().Name() + "." + fnSpec.FnName
}

func (p *Package) NewFuncDecl(funcDecl *ast.FuncDecl) error {
	skip, anony, err := p.cvt.handleSysType(funcDecl.Name, funcDecl.Loc, p.curFile.IncPath)
	if skip {
		if dbg.GetDebugLog() {
			log.Printf("NewFuncDecl: %v is a function of system header file\n", funcDecl.Name)
		}
		return err
	}
	if dbg.GetDebugLog() {
		log.Printf("NewFuncDecl: %v\n", funcDecl.Name)
	}
	if anony {
		return errs.NewAnonymousFuncNotSupportError()
	}

	fnSpec, err := p.cvt.LookupSymbol(funcDecl.MangledName)
	if err != nil {
		// not gen the function not in the symbolmap
		return err
	}

	recv, err := p.funcIsDefined(fnSpec, funcDecl)
	if err != nil {
		return err
	}

	sig, err := p.ToSigSignature(recv, funcDecl)
	if err != nil {
		return err
	}
	return p.handleFuncDecl(fnSpec, sig, funcDecl)
}

func (p *Package) funcIsDefined(fnSpec *GoFuncSpec, funcDecl *ast.FuncDecl) (recv *types.Var, err error) {
	if fnSpec.IsMethod &&
		funcDecl.Type.Params.List != nil &&
		len(funcDecl.Type.Params.List) > 0 {
		recv = p.newReceiver(funcDecl.Type)
		var namedType = getNamedType(recv.Type())
		methodName := fnSpec.FnName
		for i := 0; i < namedType.NumMethods(); i++ {
			if namedType.Method(i).Name() == methodName {
				return nil, errs.NewFuncAlreadyDefinedError(fnSpec.GoSymbName)
			}
		}
	} else {
		if obj := p.p.Types.Scope().Lookup(fnSpec.FnName); obj != nil {
			return nil, errs.NewFuncAlreadyDefinedError(fnSpec.GoSymbName)
		}
	}
	return
}

// NewTypeDecl converts C/C++ type declarations to Go.
// Besides regular type declarations, it also supports:
// - Forward declarations: Pre-registers incomplete types for later definition
// - Self-referential types: Handles types that reference themselves (like linked lists)
func (p *Package) NewTypeDecl(typeDecl *ast.TypeDecl) error {
	skip, anony, err := p.cvt.handleSysType(typeDecl.Name, typeDecl.Loc, p.curFile.IncPath)
	if skip {
		if dbg.GetDebugLog() {
			log.Printf("NewTypeDecl: %s type of system header\n", typeDecl.Name)
		}
		return err
	}
	if dbg.GetDebugLog() {
		log.Printf("NewTypeDecl: %v\n", typeDecl.Name)
	}
	if anony {
		if dbg.GetDebugLog() {
			log.Println("NewTypeDecl:Skip a anonymous type")
		}
		return nil
	}

	cname := typeDecl.Name.Name
	isForward := p.cvt.inComplete(typeDecl.Type)
	name, changed, err := p.DeclName(cname)
	if err != nil {
		if isForward {
			return nil
		}
		return err
	}
	p.CollectNameMapping(cname, name)

	incom := p.handleTypeDecl(name, cname, typeDecl)

	if changed {
		substObj(p.p.Types, p.p.Types.Scope(), cname, incom.decl.Type().Obj())
	}

	if !isForward {
		if err := p.handleCompleteType(incom, typeDecl.Type, cname); err != nil {
			return err
		}
	}
	return nil
}

// handleTypeDecl creates a new type declaration or retrieves existing one
func (p *Package) handleTypeDecl(pubname string, cname string, typeDecl *ast.TypeDecl) *Incomplete {
	if existDecl, exists := p.incomplete[cname]; exists {
		return existDecl
	}
	_, decl := p.NewEmptyTypeDecl(pubname, typeDecl.Doc)
	inc := &Incomplete{
		file: p.curFile,
		decl: decl,
	}
	p.incomplete[cname] = inc
	return inc
}

func (p *Package) handleCompleteType(incom *Incomplete, typ *ast.RecordType, name string) error {
	defer delete(p.incomplete, name)
	defer p.SetCurFile(p.curFile)
	p.SetCurFile(incom.file)
	structType, err := p.cvt.RecordTypeToStruct(typ)
	if err != nil {
		// For incomplete type's conerter error, we use default struct type
		if !incom.inited {
			incom.inited = true
			incom.decl.InitType(p.p, types.NewStruct(p.cvt.defaultRecordField(), nil))
		}
		return err
	}
	if !incom.inited {
		incom.inited = true
		incom.decl.InitType(p.p, structType)
	}
	return nil
}

// handleImplicitForwardDecl handles type references that cannot be found in the current scope.
// For such declarations, create a empty type decl and store it in the
// incomplete map, but not in the public symbol table.
func (p *Package) handleImplicitForwardDecl(name string) *gogen.TypeDecl {
	if decl, ok := p.incomplete[name]; ok {
		return decl.decl
	}
	pubName := p.nameMapper.GetGoName(name, p.trimPrefixes())
	typdef, decl := p.NewEmptyTypeDecl(pubName, nil)
	p.incomplete[name] = &Incomplete{
		file:   p.curFile,
		decl:   decl,
		typdef: typdef,
	}
	p.nameMapper.SetMapping(name, pubName)
	return decl
}

func (p *Package) NewEmptyTypeDecl(name string, doc *ast.CommentGroup) (*gogen.TypeDefs, *gogen.TypeDecl) {
	typeBlock := p.p.NewTypeDefs()
	if doc != nil {
		typeBlock.SetComments(CommentGroup(doc).CommentGroup)
	}
	return typeBlock, typeBlock.NewType(name)
}

func (p *Package) NewTypedefDecl(typedefDecl *ast.TypedefDecl) error {
	skip, _, err := p.cvt.handleSysType(typedefDecl.Name, typedefDecl.Loc, p.curFile.IncPath)
	if skip {
		if dbg.GetDebugLog() {
			log.Printf("NewTypedefDecl: %v is a typedef of system header file\n", typedefDecl.Name)
		}
		return err
	}
	if dbg.GetDebugLog() {
		log.Printf("NewTypedefDecl: %v\n", typedefDecl.Name)
	}
	name, changed, err := p.DeclName(typedefDecl.Name.Name)
	if err != nil {
		return err
	}
	p.CollectNameMapping(typedefDecl.Name.Name, name)

	var typeSpecdecl *gogen.TypeDecl
	var genDecl *gogen.TypeDefs
	var incompleteDecl *Incomplete
	if incompleteDecl = p.incomplete[typedefDecl.Name.Name]; incompleteDecl != nil {
		genDecl = incompleteDecl.typdef
		typeSpecdecl = incompleteDecl.decl
	} else {
		genDecl, typeSpecdecl = p.NewEmptyTypeDecl(name, nil)
	}

	if changed {
		substObj(p.p.Types, p.p.Types.Scope(), typedefDecl.Name.Name, typeSpecdecl.Type().Obj())
	}

	if tagRef, ok := typedefDecl.Type.(*ast.TagExpr); ok {
		inc := p.handleTyperefIncomplete(tagRef, typeSpecdecl)
		if inc {
			return nil
		}
	}

	typ, err := p.ToType(typedefDecl.Type)
	if err != nil {
		if incompleteDecl != nil {
			incompleteDecl.inited = true
		}
		typeSpecdecl.InitType(p.p, types.NewStruct(p.cvt.defaultRecordField(), nil))
		return err
	}

	if incompleteDecl != nil {
		incompleteDecl.inited = true
	}
	typeSpecdecl.InitType(p.p, typ)
	if genDecl != nil {
		if _, ok := typ.(*types.Signature); ok {
			genDecl.SetComments(NewTypecDocComments())
		}
	}

	return nil
}

func (p *Package) handleTyperefIncomplete(tagRef *ast.TagExpr, typeSpecdecl *gogen.TypeDecl) bool {
	var name string
	switch n := tagRef.Name.(type) {
	case *ast.Ident:
		name = n.Name
	case *ast.ScopingExpr:
		// todo(zzy):scoping
		panic("todo:scoping expr not supported")
	}
	_, inc := p.incomplete[name]
	if !inc {
		return false
	}
	p.deferTypes[typeSpecdecl] = func() (types.Type, error) {
		typ, err := p.ToType(tagRef)
		if err != nil {
			return nil, err
		}
		// a function type will not be a incomplete type,so we not need to check signature and add comments
		return typ, nil
	}
	return true
}

// Convert ast.Expr to types.Type
func (p *Package) ToType(expr ast.Expr) (types.Type, error) {
	return p.cvt.ToType(expr)
}

func (p *Package) NewEnumTypedefs(name string, typ types.Type, cname string) *gogen.TypeDecl {
	var def *gogen.TypeDefs
	var t *gogen.TypeDecl
	var incompleteDecl *Incomplete
	if incompleteDecl = p.incomplete[cname]; incompleteDecl != nil {
		def = incompleteDecl.typdef
		t = incompleteDecl.decl
	} else {
		def, t = p.NewEmptyTypeDecl(name, nil)
	}
	if incompleteDecl != nil {
		incompleteDecl.inited = true
	}
	t.InitType(def.Pkg(), typ)
	def.Complete()
	return t
}

func (p *Package) NewEnumTypeDecl(enumTypeDecl *ast.EnumTypeDecl) error {
	skip, _, err := p.cvt.handleSysType(enumTypeDecl.Name, enumTypeDecl.Loc, p.curFile.IncPath)
	if skip {
		if dbg.GetDebugLog() {
			log.Printf("NewEnumTypeDecl: %v is a enum type of system header file\n", enumTypeDecl.Name)
		}
		return err
	}
	if dbg.GetDebugLog() {
		log.Printf("NewEnumTypeDecl: %v\n", enumTypeDecl.Name)
	}
	enumType, enumTypeName, err := p.createEnumType(enumTypeDecl.Name)
	if err != nil {
		return err
	}
	if len(enumTypeDecl.Type.Items) > 0 {
		err = p.createEnumItems(enumTypeDecl.Type.Items, enumType, enumTypeName)
		if err != nil {
			return err
		}
	}
	return nil
}

func (p *Package) createEnumType(enumName *ast.Ident) (types.Type, string, error) {
	var name string
	var changed bool
	var err error
	var t *gogen.TypeDecl
	if enumName != nil {
		name, changed, err = p.DeclName(enumName.Name)
		if err != nil {
			return nil, "", errs.NewTypeDefinedError(name, enumName.Name)
		}
		p.CollectNameMapping(enumName.Name, name)
	}
	enumType := p.cvt.ToDefaultEnumType()
	if name != "" {
		t = p.NewEnumTypedefs(name, enumType, enumName.Name)
		enumType = p.p.Types.Scope().Lookup(name).Type()
	}
	if changed {
		substObj(p.p.Types, p.p.Types.Scope(), enumName.Name, t.Type().Obj())
	}
	return enumType, name, nil
}

func (p *Package) createEnumItems(items []*ast.EnumItem, enumType types.Type, enumTypeName string) error {
	defs := p.NewConstGroup()
	for _, item := range items {
		// maybe get a new name,because the after executed name,have some situation will found same name
		constName := p.nameMapper.GetGoName(item.Name.Name, p.trimPrefixes())
		if enumTypeName != "" {
			constName = enumTypeName + "_" + constName
		}
		name, changed, err := p.DeclName(constName)
		if err != nil {
			return errs.NewTypeDefinedError(name, item.Name.Name)
		}
		val, err := Expr(item.Value).ToInt()
		if err != nil {
			return err
		}
		defs.New(val, enumType, name)
		if changed {
			if obj := p.p.Types.Scope().Lookup(name); obj != nil {
				substObj(p.p.Types, p.p.Types.Scope(), item.Name.Name, obj)
			}
		}
	}
	return nil
}

func (p *Package) NewMacro(macro *ast.Macro) error {
	if p.curFile.IsSys {
		return nil
	}
	// simple const macro define (#define NAME value)
	if len(macro.Tokens) == 2 && macro.Tokens[1].Token == ctoken.LITERAL {
		value := macro.Tokens[1].Lit
		defs := p.NewConstGroup()
		name, _, err := p.DeclName(macro.Name)
		if err != nil {
			return err
		}
		if str, err := litToString(value); err == nil {
			defs.New(str, types.Typ[types.String], name)
		} else if val, err := litToInt(value); err == nil {
			defs.New(int(val), p.cvt.typeMap.CType("Int"), name)
		} else if fval, err := litToFloat(value, 64); err == nil {
			defs.New(fval, p.cvt.typeMap.CType("Float"), name)
		}
	}
	return nil
}

func (p *Package) NewConstGroup() *ConstGroup {
	return NewConstGroup(p.p, p.p.Types.Scope())
}

type ConstGroup struct {
	defs *gogen.ConstDefs
}

func NewConstGroup(pkg *gogen.Package, scope *types.Scope) *ConstGroup {
	return &ConstGroup{
		defs: pkg.NewConstDefs(scope),
	}
}

func (p *ConstGroup) New(val any, typ types.Type, name string) {
	p.defs.New(func(cb *gogen.CodeBuilder) int {
		cb.Val(val)
		return 1
	}, 0, token.NoPos, typ, name)
}

// WritePkgFiles writes all converted header files to Go files.
// Calls deferTypeBuild() first to complete all incomplete type definitions,
// because some types may be implemented across multiple files.
func (p *Package) WritePkgFiles() error {
	err := p.deferTypeBuild()
	if err != nil {
		return err
	}
	for _, file := range p.files {
		if file.IsHeaderFile && !file.IsSys {
			err := p.Write(file.File)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// Write generates a Go file based on the package content.
// The output file will be generated in a subdirectory named after the package within the outputDir.
// If outputDir is not provided, the current directory will be used.
// The header file name is the go file name.
//
// Files that are already processed in dependent packages will not be output.
func (p *Package) Write(headerFile string) error {
	fileName := names.HeaderFileToGo(headerFile)
	filePath := filepath.Join(p.GetOutputDir(), fileName)
	if dbg.GetDebugLog() {
		log.Printf("Write HeaderFile [%s] from  gogen:[%s] to [%s]\n", headerFile, fileName, filePath)
	}
	return p.writeToFile(fileName, filePath)
}

func (p *Package) WriteLinkFile() (string, error) {
	fileName := p.conf.Name + "_autogen_link.go"
	filePath := filepath.Join(p.GetOutputDir(), fileName)
	_, err := p.p.SetCurFile(fileName, true)
	if err != nil {
		return "", fmt.Errorf("failed to set current file: %w", err)
	}
	err = p.linkLib(p.conf.CppgConf.Libs)
	if dbg.GetDebugLog() {
		log.Printf("Write LinkFile [%s] from  gogen:[%s] to [%s]\n", fileName, fileName, filePath)
	}
	if err != nil {
		return "", fmt.Errorf("failed to link lib: %w", err)
	}
	if err := p.writeToFile(fileName, filePath); err != nil {
		return "", fmt.Errorf("failed to write file: %w", err)
	}
	return filePath, nil
}

// WriteDefaultFileToBuffer writes the content of the default Go file to a buffer.
// The default file is named after the package (p.Name() + ".go").
// This method is particularly useful for testing type outputs, especially in package tests
// where there typically isn't (and doesn't need to be) a corresponding header file.
// Before calling SetCurFile, all type creations are written to this default gogen file.
// It allows for easy inspection of generated types without the need for actual file I/O.
func (p *Package) WriteDefaultFileToBuffer() (*bytes.Buffer, error) {
	return p.WriteToBuffer(p.conf.Name + ".go")
}

// Write the corresponding files in gogen package to the file
func (p *Package) writeToFile(genFName string, filePath string) error {
	buf, err := p.WriteToBuffer(genFName)
	if err != nil {
		return err
	}
	return os.WriteFile(filePath, buf.Bytes(), 0644)
}

// Write the corresponding files in gogen package to the buffer
func (p *Package) WriteToBuffer(genFName string) (*bytes.Buffer, error) {
	buf := new(bytes.Buffer)
	err := p.p.WriteTo(buf, genFName)
	if err != nil {
		return nil, fmt.Errorf("failed to write to buffer: %w", err)
	}
	return buf, nil
}

func (p *Package) deferTypeBuild() error {
	for _, inc := range p.incomplete {
		p.SetCurFile(inc.file)
		if !inc.inited {
			inc.inited = true
			inc.decl.InitType(p.p, types.NewStruct(p.cvt.defaultRecordField(), nil))
		}
	}
	for decl, getTyp := range p.deferTypes {
		typ, err := getTyp()
		if typ != nil {
			decl.InitType(p.p, typ)
		}
		if err != nil {
			return err
		}
	}
	p.incomplete = make(map[string]*Incomplete, 0)
	p.deferTypes = make(map[*gogen.TypeDecl]func() (types.Type, error), 0)
	return nil
}

func (p *Package) WritePubFile() error {
	return cfg.WritePubFile(filepath.Join(p.GetOutputDir(), "llcppg.pub"), p.Pubs)
}

// For a decl name, it should be unique
func (p *Package) DeclName(name string) (pubName string, changed bool, err error) {
	pubName, changed = p.nameMapper.GetUniqueGoName(name, p.trimPrefixes())
	// if the type is incomplete,it's ok to have the same name
	if obj := p.p.Types.Scope().Lookup(name); obj != nil && p.incomplete[name] == nil {
		return "", false, errs.NewTypeDefinedError(pubName, name)
	}
	return pubName, changed, nil
}

func (p *Package) trimPrefixes() []string {
	if p.curFile.InCurPkg {
		return p.CppgConf.TrimPrefixes
	}
	return []string{}
}

// Collect the name mapping between origin name and pubname
// if in current package, it will be collected in public symbol table
func (p *Package) CollectNameMapping(originName, newName string) {
	value := ""
	if originName != newName {
		value = newName
	}
	p.nameMapper.SetMapping(originName, value)
	if p.curFile.InCurPkg {
		p.Pubs[originName] = value
	}
}

// Return all include paths of dependent packages
func (p *Package) DepIncPaths() []string {
	visited := make(map[string]bool)
	var paths []string
	var collectPaths func(pkg *PkgInfo)
	var notFounds map[string][]string // pkgpath -> include path
	var allfailed []string            // which pkg's header file failed to find any include path

	collectPaths = func(pkg *PkgInfo) {
		for _, dep := range pkg.Deps {
			incPaths, notFnds, err := dep.GetIncPaths()
			if err != nil {
				allfailed = append(allfailed, dep.PkgPath)
			} else if len(notFnds) > 0 {
				if notFounds == nil {
					notFounds = make(map[string][]string)
				}
				notFounds[dep.PkgPath] = notFnds
			}
			for _, path := range incPaths {
				if !visited[path] {
					visited[path] = true
					paths = append(paths, path)
				}
			}
			collectPaths(dep)
		}
	}
	collectPaths(p.PkgInfo)

	if len(notFounds) > 0 {
		for pkgPath, notFnds := range notFounds {
			log.Printf("failed to find some include paths: from %s\n", pkgPath)
			log.Println(notFnds)
		}
	}
	if len(allfailed) > 0 {
		log.Println("failed to get any include paths from these package: \n", allfailed)
	}
	return paths
}
